services:
  #  =================== Databases ===================

  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: hackyeah
      POSTGRES_PASSWORD: zaq1@WSX
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hackyeah
      - MONGO_INITDB_ROOT_PASSWORD=hackyeah

  #  =============== Keycloak Service ===============

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net
    command:
      - "start-dev"

  #  ================ Mailer Service ================

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080 # UI
      - 1025:1025 # SMTP

  #  ================= Monitoring ==================

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net


#  ================== Networks ===================
networks:
  microservices-net:
    driver: bridge

#  =================== Volumes ===================
volumes:
  postgres:
  pgadmin:
  mongo: