package com.hackyeah2024.feed.recommender;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommender.proto
// Protobuf Java Version: 4.26.1

public final class RecommenderOuterClass {
  private RecommenderOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      RecommenderOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequesterType}
   */
  public enum RequesterType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Default value if not set
     * </pre>
     *
     * <code>REQUESTER_UNKNOWN = 0;</code>
     */
    REQUESTER_UNKNOWN(0),
    /**
     * <pre>
     * Represents a company requester
     * </pre>
     *
     * <code>REQUESTER_COMPANY = 1;</code>
     */
    REQUESTER_COMPANY(1),
    /**
     * <pre>
     * Represents an NGO requester
     * </pre>
     *
     * <code>REQUESTER_NGO = 2;</code>
     */
    REQUESTER_NGO(2),
    /**
     * <pre>
     * Represents a volunteer requester
     * </pre>
     *
     * <code>REQUESTER_VOLUNTEER = 3;</code>
     */
    REQUESTER_VOLUNTEER(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        RequesterType.class.getName());
    }
    /**
     * <pre>
     * Default value if not set
     * </pre>
     *
     * <code>REQUESTER_UNKNOWN = 0;</code>
     */
    public static final int REQUESTER_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Represents a company requester
     * </pre>
     *
     * <code>REQUESTER_COMPANY = 1;</code>
     */
    public static final int REQUESTER_COMPANY_VALUE = 1;
    /**
     * <pre>
     * Represents an NGO requester
     * </pre>
     *
     * <code>REQUESTER_NGO = 2;</code>
     */
    public static final int REQUESTER_NGO_VALUE = 2;
    /**
     * <pre>
     * Represents a volunteer requester
     * </pre>
     *
     * <code>REQUESTER_VOLUNTEER = 3;</code>
     */
    public static final int REQUESTER_VOLUNTEER_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequesterType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequesterType forNumber(int value) {
      switch (value) {
        case 0: return REQUESTER_UNKNOWN;
        case 1: return REQUESTER_COMPANY;
        case 2: return REQUESTER_NGO;
        case 3: return REQUESTER_VOLUNTEER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequesterType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequesterType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequesterType>() {
            public RequesterType findValueByNumber(int number) {
              return RequesterType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RecommenderOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequesterType[] VALUES = values();

    public static RequesterType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequesterType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequesterType)
  }

  /**
   * <pre>
   * Enumeration to specify the type of request being made.
   * </pre>
   *
   * Protobuf enum {@code RequestedType}
   */
  public enum RequestedType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Default value if not set
     * </pre>
     *
     * <code>REQUESTED_UNKNOWN = 0;</code>
     */
    REQUESTED_UNKNOWN(0),
    /**
     * <pre>
     * Represents a company requested
     * </pre>
     *
     * <code>REQUESTED_COMPANY = 1;</code>
     */
    REQUESTED_COMPANY(1),
    /**
     * <pre>
     * Represents an NGO requested
     * </pre>
     *
     * <code>REQUESTED_NGO = 2;</code>
     */
    REQUESTED_NGO(2),
    /**
     * <pre>
     * Represents a volunteer requested
     * </pre>
     *
     * <code>REQUESTED_VOLUNTEER = 3;</code>
     */
    REQUESTED_VOLUNTEER(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        RequestedType.class.getName());
    }
    /**
     * <pre>
     * Default value if not set
     * </pre>
     *
     * <code>REQUESTED_UNKNOWN = 0;</code>
     */
    public static final int REQUESTED_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Represents a company requested
     * </pre>
     *
     * <code>REQUESTED_COMPANY = 1;</code>
     */
    public static final int REQUESTED_COMPANY_VALUE = 1;
    /**
     * <pre>
     * Represents an NGO requested
     * </pre>
     *
     * <code>REQUESTED_NGO = 2;</code>
     */
    public static final int REQUESTED_NGO_VALUE = 2;
    /**
     * <pre>
     * Represents a volunteer requested
     * </pre>
     *
     * <code>REQUESTED_VOLUNTEER = 3;</code>
     */
    public static final int REQUESTED_VOLUNTEER_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestedType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestedType forNumber(int value) {
      switch (value) {
        case 0: return REQUESTED_UNKNOWN;
        case 1: return REQUESTED_COMPANY;
        case 2: return REQUESTED_NGO;
        case 3: return REQUESTED_VOLUNTEER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestedType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestedType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestedType>() {
            public RequestedType findValueByNumber(int number) {
              return RequestedType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RecommenderOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final RequestedType[] VALUES = values();

    public static RequestedType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestedType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestedType)
  }

  public interface RecommendationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RecommendationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * User ID for which to fetch recommendations
     * </pre>
     *
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <pre>
     * User ID for which to fetch recommendations
     * </pre>
     *
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <pre>
     * Type of requester (company, NGO, volunteer)
     * </pre>
     *
     * <code>.RequesterType requester_type = 2;</code>
     * @return The enum numeric value on the wire for requesterType.
     */
    int getRequesterTypeValue();
    /**
     * <pre>
     * Type of requester (company, NGO, volunteer)
     * </pre>
     *
     * <code>.RequesterType requester_type = 2;</code>
     * @return The requesterType.
     */
    RecommenderOuterClass.RequesterType getRequesterType();

    /**
     * <pre>
     * Type of request being made
     * </pre>
     *
     * <code>.RequestedType requested_type = 3;</code>
     * @return The enum numeric value on the wire for requestedType.
     */
    int getRequestedTypeValue();
    /**
     * <pre>
     * Type of request being made
     * </pre>
     *
     * <code>.RequestedType requested_type = 3;</code>
     * @return The requestedType.
     */
    RecommenderOuterClass.RequestedType getRequestedType();
  }
  /**
   * <pre>
   * The request message containing the user ID for recommendations.
   * </pre>
   *
   * Protobuf type {@code RecommendationRequest}
   */
  public static final class RecommendationRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RecommendationRequest)
      RecommendationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        RecommendationRequest.class.getName());
    }
    // Use RecommendationRequest.newBuilder() to construct.
    private RecommendationRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RecommendationRequest() {
      userId_ = "";
      requesterType_ = 0;
      requestedType_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecommenderOuterClass.internal_static_RecommendationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecommenderOuterClass.internal_static_RecommendationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecommenderOuterClass.RecommendationRequest.class, RecommenderOuterClass.RecommendationRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <pre>
     * User ID for which to fetch recommendations
     * </pre>
     *
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * User ID for which to fetch recommendations
     * </pre>
     *
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTER_TYPE_FIELD_NUMBER = 2;
    private int requesterType_ = 0;
    /**
     * <pre>
     * Type of requester (company, NGO, volunteer)
     * </pre>
     *
     * <code>.RequesterType requester_type = 2;</code>
     * @return The enum numeric value on the wire for requesterType.
     */
    @java.lang.Override public int getRequesterTypeValue() {
      return requesterType_;
    }
    /**
     * <pre>
     * Type of requester (company, NGO, volunteer)
     * </pre>
     *
     * <code>.RequesterType requester_type = 2;</code>
     * @return The requesterType.
     */
    @java.lang.Override public RecommenderOuterClass.RequesterType getRequesterType() {
      RecommenderOuterClass.RequesterType result = RecommenderOuterClass.RequesterType.forNumber(requesterType_);
      return result == null ? RecommenderOuterClass.RequesterType.UNRECOGNIZED : result;
    }

    public static final int REQUESTED_TYPE_FIELD_NUMBER = 3;
    private int requestedType_ = 0;
    /**
     * <pre>
     * Type of request being made
     * </pre>
     *
     * <code>.RequestedType requested_type = 3;</code>
     * @return The enum numeric value on the wire for requestedType.
     */
    @java.lang.Override public int getRequestedTypeValue() {
      return requestedType_;
    }
    /**
     * <pre>
     * Type of request being made
     * </pre>
     *
     * <code>.RequestedType requested_type = 3;</code>
     * @return The requestedType.
     */
    @java.lang.Override public RecommenderOuterClass.RequestedType getRequestedType() {
      RecommenderOuterClass.RequestedType result = RecommenderOuterClass.RequestedType.forNumber(requestedType_);
      return result == null ? RecommenderOuterClass.RequestedType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
      }
      if (requesterType_ != RecommenderOuterClass.RequesterType.REQUESTER_UNKNOWN.getNumber()) {
        output.writeEnum(2, requesterType_);
      }
      if (requestedType_ != RecommenderOuterClass.RequestedType.REQUESTED_UNKNOWN.getNumber()) {
        output.writeEnum(3, requestedType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
      }
      if (requesterType_ != RecommenderOuterClass.RequesterType.REQUESTER_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requesterType_);
      }
      if (requestedType_ != RecommenderOuterClass.RequestedType.REQUESTED_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, requestedType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecommenderOuterClass.RecommendationRequest)) {
        return super.equals(obj);
      }
      RecommenderOuterClass.RecommendationRequest other = (RecommenderOuterClass.RecommendationRequest) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (requesterType_ != other.requesterType_) return false;
      if (requestedType_ != other.requestedType_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + REQUESTER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + requesterType_;
      hash = (37 * hash) + REQUESTED_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestedType_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static RecommenderOuterClass.RecommendationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static RecommenderOuterClass.RecommendationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RecommenderOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecommenderOuterClass.RecommendationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the user ID for recommendations.
     * </pre>
     *
     * Protobuf type {@code RecommendationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RecommendationRequest)
        RecommenderOuterClass.RecommendationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecommenderOuterClass.internal_static_RecommendationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecommenderOuterClass.internal_static_RecommendationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecommenderOuterClass.RecommendationRequest.class, RecommenderOuterClass.RecommendationRequest.Builder.class);
      }

      // Construct using RecommenderOuterClass.RecommendationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = "";
        requesterType_ = 0;
        requestedType_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecommenderOuterClass.internal_static_RecommendationRequest_descriptor;
      }

      @java.lang.Override
      public RecommenderOuterClass.RecommendationRequest getDefaultInstanceForType() {
        return RecommenderOuterClass.RecommendationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public RecommenderOuterClass.RecommendationRequest build() {
        RecommenderOuterClass.RecommendationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RecommenderOuterClass.RecommendationRequest buildPartial() {
        RecommenderOuterClass.RecommendationRequest result = new RecommenderOuterClass.RecommendationRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RecommenderOuterClass.RecommendationRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.requesterType_ = requesterType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.requestedType_ = requestedType_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecommenderOuterClass.RecommendationRequest) {
          return mergeFrom((RecommenderOuterClass.RecommendationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecommenderOuterClass.RecommendationRequest other) {
        if (other == RecommenderOuterClass.RecommendationRequest.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.requesterType_ != 0) {
          setRequesterTypeValue(other.getRequesterTypeValue());
        }
        if (other.requestedType_ != 0) {
          setRequestedTypeValue(other.getRequestedTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                requesterType_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                requestedType_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <pre>
       * User ID for which to fetch recommendations
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * User ID for which to fetch recommendations
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * User ID for which to fetch recommendations
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * User ID for which to fetch recommendations
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * User ID for which to fetch recommendations
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int requesterType_ = 0;
      /**
       * <pre>
       * Type of requester (company, NGO, volunteer)
       * </pre>
       *
       * <code>.RequesterType requester_type = 2;</code>
       * @return The enum numeric value on the wire for requesterType.
       */
      @java.lang.Override public int getRequesterTypeValue() {
        return requesterType_;
      }
      /**
       * <pre>
       * Type of requester (company, NGO, volunteer)
       * </pre>
       *
       * <code>.RequesterType requester_type = 2;</code>
       * @param value The enum numeric value on the wire for requesterType to set.
       * @return This builder for chaining.
       */
      public Builder setRequesterTypeValue(int value) {
        requesterType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of requester (company, NGO, volunteer)
       * </pre>
       *
       * <code>.RequesterType requester_type = 2;</code>
       * @return The requesterType.
       */
      @java.lang.Override
      public RecommenderOuterClass.RequesterType getRequesterType() {
        RecommenderOuterClass.RequesterType result = RecommenderOuterClass.RequesterType.forNumber(requesterType_);
        return result == null ? RecommenderOuterClass.RequesterType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Type of requester (company, NGO, volunteer)
       * </pre>
       *
       * <code>.RequesterType requester_type = 2;</code>
       * @param value The requesterType to set.
       * @return This builder for chaining.
       */
      public Builder setRequesterType(RecommenderOuterClass.RequesterType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        requesterType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of requester (company, NGO, volunteer)
       * </pre>
       *
       * <code>.RequesterType requester_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequesterType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requesterType_ = 0;
        onChanged();
        return this;
      }

      private int requestedType_ = 0;
      /**
       * <pre>
       * Type of request being made
       * </pre>
       *
       * <code>.RequestedType requested_type = 3;</code>
       * @return The enum numeric value on the wire for requestedType.
       */
      @java.lang.Override public int getRequestedTypeValue() {
        return requestedType_;
      }
      /**
       * <pre>
       * Type of request being made
       * </pre>
       *
       * <code>.RequestedType requested_type = 3;</code>
       * @param value The enum numeric value on the wire for requestedType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestedTypeValue(int value) {
        requestedType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of request being made
       * </pre>
       *
       * <code>.RequestedType requested_type = 3;</code>
       * @return The requestedType.
       */
      @java.lang.Override
      public RecommenderOuterClass.RequestedType getRequestedType() {
        RecommenderOuterClass.RequestedType result = RecommenderOuterClass.RequestedType.forNumber(requestedType_);
        return result == null ? RecommenderOuterClass.RequestedType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Type of request being made
       * </pre>
       *
       * <code>.RequestedType requested_type = 3;</code>
       * @param value The requestedType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestedType(RecommenderOuterClass.RequestedType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        requestedType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of request being made
       * </pre>
       *
       * <code>.RequestedType requested_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestedType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestedType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RecommendationRequest)
    }

    // @@protoc_insertion_point(class_scope:RecommendationRequest)
    private static final RecommenderOuterClass.RecommendationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecommenderOuterClass.RecommendationRequest();
    }

    public static RecommenderOuterClass.RecommendationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendationRequest>
        PARSER = new com.google.protobuf.AbstractParser<RecommendationRequest>() {
      @java.lang.Override
      public RecommendationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RecommendationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecommendationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RecommenderOuterClass.RecommendationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecommendationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RecommendationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @return A list containing the recommendedItems.
     */
    java.util.List<java.lang.String>
        getRecommendedItemsList();
    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @return The count of recommendedItems.
     */
    int getRecommendedItemsCount();
    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @param index The index of the element to return.
     * @return The recommendedItems at the given index.
     */
    java.lang.String getRecommendedItems(int index);
    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the recommendedItems at the given index.
     */
    com.google.protobuf.ByteString
        getRecommendedItemsBytes(int index);
  }
  /**
   * <pre>
   * The response message containing a list of recommended items.
   * </pre>
   *
   * Protobuf type {@code RecommendationResponse}
   */
  public static final class RecommendationResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:RecommendationResponse)
      RecommendationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        RecommendationResponse.class.getName());
    }
    // Use RecommendationResponse.newBuilder() to construct.
    private RecommendationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RecommendationResponse() {
      recommendedItems_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecommenderOuterClass.internal_static_RecommendationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecommenderOuterClass.internal_static_RecommendationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecommenderOuterClass.RecommendationResponse.class, RecommenderOuterClass.RecommendationResponse.Builder.class);
    }

    public static final int RECOMMENDED_ITEMS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList recommendedItems_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @return A list containing the recommendedItems.
     */
    public com.google.protobuf.ProtocolStringList
        getRecommendedItemsList() {
      return recommendedItems_;
    }
    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @return The count of recommendedItems.
     */
    public int getRecommendedItemsCount() {
      return recommendedItems_.size();
    }
    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @param index The index of the element to return.
     * @return The recommendedItems at the given index.
     */
    public java.lang.String getRecommendedItems(int index) {
      return recommendedItems_.get(index);
    }
    /**
     * <pre>
     * List of recommended item IDs
     * </pre>
     *
     * <code>repeated string recommended_items = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the recommendedItems at the given index.
     */
    public com.google.protobuf.ByteString
        getRecommendedItemsBytes(int index) {
      return recommendedItems_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < recommendedItems_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, recommendedItems_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < recommendedItems_.size(); i++) {
          dataSize += computeStringSizeNoTag(recommendedItems_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRecommendedItemsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RecommenderOuterClass.RecommendationResponse)) {
        return super.equals(obj);
      }
      RecommenderOuterClass.RecommendationResponse other = (RecommenderOuterClass.RecommendationResponse) obj;

      if (!getRecommendedItemsList()
          .equals(other.getRecommendedItemsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecommendedItemsCount() > 0) {
        hash = (37 * hash) + RECOMMENDED_ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getRecommendedItemsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static RecommenderOuterClass.RecommendationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static RecommenderOuterClass.RecommendationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static RecommenderOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RecommenderOuterClass.RecommendationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message containing a list of recommended items.
     * </pre>
     *
     * Protobuf type {@code RecommendationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RecommendationResponse)
        RecommenderOuterClass.RecommendationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RecommenderOuterClass.internal_static_RecommendationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RecommenderOuterClass.internal_static_RecommendationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RecommenderOuterClass.RecommendationResponse.class, RecommenderOuterClass.RecommendationResponse.Builder.class);
      }

      // Construct using RecommenderOuterClass.RecommendationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        recommendedItems_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RecommenderOuterClass.internal_static_RecommendationResponse_descriptor;
      }

      @java.lang.Override
      public RecommenderOuterClass.RecommendationResponse getDefaultInstanceForType() {
        return RecommenderOuterClass.RecommendationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public RecommenderOuterClass.RecommendationResponse build() {
        RecommenderOuterClass.RecommendationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public RecommenderOuterClass.RecommendationResponse buildPartial() {
        RecommenderOuterClass.RecommendationResponse result = new RecommenderOuterClass.RecommendationResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RecommenderOuterClass.RecommendationResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          recommendedItems_.makeImmutable();
          result.recommendedItems_ = recommendedItems_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RecommenderOuterClass.RecommendationResponse) {
          return mergeFrom((RecommenderOuterClass.RecommendationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RecommenderOuterClass.RecommendationResponse other) {
        if (other == RecommenderOuterClass.RecommendationResponse.getDefaultInstance()) return this;
        if (!other.recommendedItems_.isEmpty()) {
          if (recommendedItems_.isEmpty()) {
            recommendedItems_ = other.recommendedItems_;
            bitField0_ |= 0x00000001;
          } else {
            ensureRecommendedItemsIsMutable();
            recommendedItems_.addAll(other.recommendedItems_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureRecommendedItemsIsMutable();
                recommendedItems_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList recommendedItems_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureRecommendedItemsIsMutable() {
        if (!recommendedItems_.isModifiable()) {
          recommendedItems_ = new com.google.protobuf.LazyStringArrayList(recommendedItems_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @return A list containing the recommendedItems.
       */
      public com.google.protobuf.ProtocolStringList
          getRecommendedItemsList() {
        recommendedItems_.makeImmutable();
        return recommendedItems_;
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @return The count of recommendedItems.
       */
      public int getRecommendedItemsCount() {
        return recommendedItems_.size();
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @param index The index of the element to return.
       * @return The recommendedItems at the given index.
       */
      public java.lang.String getRecommendedItems(int index) {
        return recommendedItems_.get(index);
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the recommendedItems at the given index.
       */
      public com.google.protobuf.ByteString
          getRecommendedItemsBytes(int index) {
        return recommendedItems_.getByteString(index);
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @param index The index to set the value at.
       * @param value The recommendedItems to set.
       * @return This builder for chaining.
       */
      public Builder setRecommendedItems(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureRecommendedItemsIsMutable();
        recommendedItems_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @param value The recommendedItems to add.
       * @return This builder for chaining.
       */
      public Builder addRecommendedItems(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureRecommendedItemsIsMutable();
        recommendedItems_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @param values The recommendedItems to add.
       * @return This builder for chaining.
       */
      public Builder addAllRecommendedItems(
          java.lang.Iterable<java.lang.String> values) {
        ensureRecommendedItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recommendedItems_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecommendedItems() {
        recommendedItems_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of recommended item IDs
       * </pre>
       *
       * <code>repeated string recommended_items = 1;</code>
       * @param value The bytes of the recommendedItems to add.
       * @return This builder for chaining.
       */
      public Builder addRecommendedItemsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureRecommendedItemsIsMutable();
        recommendedItems_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RecommendationResponse)
    }

    // @@protoc_insertion_point(class_scope:RecommendationResponse)
    private static final RecommenderOuterClass.RecommendationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RecommenderOuterClass.RecommendationResponse();
    }

    public static RecommenderOuterClass.RecommendationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendationResponse>
        PARSER = new com.google.protobuf.AbstractParser<RecommendationResponse>() {
      @java.lang.Override
      public RecommendationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RecommendationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecommendationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public RecommenderOuterClass.RecommendationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecommendationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RecommendationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecommendationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RecommendationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021recommender.proto\"x\n\025RecommendationReq" +
      "uest\022\017\n\007user_id\030\001 \001(\t\022&\n\016requester_type\030" +
      "\002 \001(\0162\016.RequesterType\022&\n\016requested_type\030" +
      "\003 \001(\0162\016.RequestedType\"3\n\026RecommendationR" +
      "esponse\022\031\n\021recommended_items\030\001 \003(\t*i\n\rRe" +
      "questerType\022\025\n\021REQUESTER_UNKNOWN\020\000\022\025\n\021RE" +
      "QUESTER_COMPANY\020\001\022\021\n\rREQUESTER_NGO\020\002\022\027\n\023" +
      "REQUESTER_VOLUNTEER\020\003*i\n\rRequestedType\022\025" +
      "\n\021REQUESTED_UNKNOWN\020\000\022\025\n\021REQUESTED_COMPA" +
      "NY\020\001\022\021\n\rREQUESTED_NGO\020\002\022\027\n\023REQUESTED_VOL" +
      "UNTEER\020\0032T\n\013Recommender\022E\n\022GetRecommenda" +
      "tions\022\026.RecommendationRequest\032\027.Recommen" +
      "dationResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RecommendationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RecommendationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RecommendationRequest_descriptor,
        new java.lang.String[] { "UserId", "RequesterType", "RequestedType", });
    internal_static_RecommendationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RecommendationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RecommendationResponse_descriptor,
        new java.lang.String[] { "RecommendedItems", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
